# ** What are data structures, and why are they important ?**
​Data structures are ways to organize and store data in a computer so that it can be used efficiently.
example.. List , tuple , set ,Dictionary
why are they important...?
this is important for...
Efficient Data Management
Code Clarity and Maintainability
Optimized Performance

#  Explain the difference between mutable and immutable data types with examples..?


 Mutable Data Types ==> These are data types whose values can be changed after they are created
Example of Mutable Data
    my_list = [1, 2, 3]
    my_list.append(4)
    print(my_list) # we can change it after they are created
 Immutable Data Types ==> These are data types whose values cannot be changed once they are created

    my_string = "hello"
    my_string[0] = 'H' we can't change after created it

#  What are the main differences between lists and tuples in Python ?
lists and tuples are both used to store collections of items, but they have distinct characteristics that make them suitable for different scenarios.

list are mutable collections, allowing changes like adding or removing items, and are defined using square brackets []. They are ideal for dynamic data that may change over time. In contrast, tuples are immutable, meaning their contents cannot be altered after creation, and are defined using parentheses (). Tuples are suitable for fixed data that should remain constant, offering faster performance and lower memory usage compared to lists.

#  Describe how dictionaries store data

dictionaries store data as key-value pairs using a data structure called a hash table. This allows for efficient data retrieval, insertion, and deletion operations. Key-Value Pairs Each item in a dictionary consists of a unique key and its associated value. Keys must be immutable types (like strings, numbers, or tuples) ensuring they remain constant and hashable.

# Why might you use a set instead of a list in Python

When to Use a Set
Eliminating Duplicates --> Sets automatically discard duplicate entries, making them ideal for ensuring all elements are unique.
Fast Membership Testing --> Checking if an item exists in a set is generally faster (average-case O(1)) compared to a list (O(n)), especially beneficial for large datasets.

When to Use a List

Ordered Data --> Lists maintain the order of elements, which is essential when the sequence matters

Allowing Duplicates -->Lists can contain duplicate elements, suitable for scenarios where repetition is necessary

Indexing and Slicing --> Lists support accessing elements by index and slicing, offering flexibility in data manipulation.

# What is a string in Python, and how is it different from a list ?

​In Python, a string is a sequence of characters enclosed in quotes, such as "Hello". Strings are immutable, meaning their contents cannot be changed after creation. A list is an ordered collection of items enclosed in square brackets, like [1, 2, 3]. Lists are mutable, allowing you to modify their contents by adding, removing, or changing elements.

# How do tuples ensure data integrity in Python ?
Tuples are immutable, meaning their contents cannot be changed after creation. This ensures that the data remains constant and reliable throughout the program.

**8 What is a hash table, and how does it relate to dictionaries in Python ?**
A hash table is a data structure that stores key-value pairs. Python's dictionaries are implemented using hash tables, allowing for efficient data retrieval based on unique keys.

#  Can lists contain different data types in Python ?

Yes, lists in Python can hold elements of different data types, such as integers, strings, and even other lists.

# 10 What advantages do dictionaries offer over lists for certain tasks?
Dictionaries provide fast lookups, making them ideal for tasks where you need to retrieve data using unique keys, such as mapping user IDs to user information.

**11 Describe a scenario where using a tuple would be preferable over a list.**
Tuples are preferable when you need to store a fixed collection of items that shouldn't change, like coordinates (x, y) or RGB color values.

# how do sets handle duplicate values in Python ?
Sets automatically remove duplicate values, ensuring that each element is unique. If you try to add a duplicate, it will be ignored.

#  How does the “in” keyword work differently for lists and dictionaries in Python?
In lists, the "in" keyword checks if a value exists. In dictionaries, it checks if a key exists.

Can you modify the elements of a tuple? Explain why or why not.
No, tuples are immutable. Once created, their elements cannot be changed, added, or removed, ensuring data integrity.

# What is a nested dictionary, and give an example of its use case.
A nested dictionary is a dictionary within another dictionary. It's useful for representing hierarchical data, like storing information about employees in different departments. ​
W3Schools.com

# Describe the time complexity of accessing elements in a dictionary.
Accessing elements in a dictionary is typically O(1), meaning it takes constant time regardless of the size of the dictionary.

# In what situations are lists preferred over dictionaries?
Lists are preferred when the order of elements matters, and you need to access items by their position or index.

# Why are dictionaries considered unordered, and how does that affect data retrieval?
Dictionaries are unordered because they are implemented using hash tables. This means that the order of elements is not guaranteed, but it allows for fast access to values using keys.

# Explain the difference between a list and a dictionary in terms of data retrieval.
In a list, data is retrieved by index, which is its position in the sequence. In a dictionary, data is retrieved by key, which is a unique identifier associated with a value.

In [21]:
# Write a code to create a string with your name and print it
name = "Keshav Kumar"
print(name)

Keshav Kumar

In [1]:
# 2 Write a code to find the length of the string "Hello World"
str = "Hello World"
print(len(str))

11

In [22]:
# Write a code to slice the first 3 characters from the string "Python Programming"
str = "Python Programming"
print(str[0:3])

Pyt

In [23]:
#  Write a code to convert the string "hello" to uppercase
str = "hello"
print(str.upper())

HELLO

In [24]:
# Write a code to replace the word "apple" with "orange" in the string "I like apple"
sentence = "I like apple"
print(sentence.replace("apple", "orange"))

I like orange

In [25]:
# Write a code to create a list with numbers 1 to 5 and print it
list = [1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]

In [26]:
# Write a code to append the number 10 to the list [1, 2, 3, 4]
list = [1,2,3,4]
list.append(10)
print(list)

[1, 2, 3, 4, 10]

In [27]:
# Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]
list = [1, 2, 3, 4, 5]
list.remove(3)
print(list)

[1, 2, 4, 5]

In [28]:
# Write a code to access the second element in the list ['a', 'b', 'c', 'd']
list = ['a', 'b', 'c', 'd']
print(list[1])

b

In [29]:
#  Write a code to reverse the list [10, 20, 30, 40, 50].
list = [10, 20, 30, 40, 50]
print(list[::-1])

[50, 40, 30, 20, 10]

In [30]:
#  Write a code to create a tuple with the elements 100, 200, 300 and print it.
tuple = (100, 200, 300)
print(tuple)

(100, 200, 300)

In [31]:
#Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').
tuple = ('red', 'green', 'blue', 'yellow')
print(tuple[-2])

blue

In [32]:
#  Write a code to find the minimum number in the tuple (10, 20, 5, 15).
tuple = (10, 20, 5, 15)
print(min(tuple))

5

In [10]:
#  Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').
tuple = ('dog', 'cat', 'rabbit')
print(tuple.index('cat'))

1

In [ ]:
# . Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.
tuple = ('apple', 'banana', 'orange')
print('kiwi' in tuple)

In [14]:
#  Write a code to create a set with the elements 'a', 'b', 'c' and print it
my_set = {'a', 'b', 'c'}
print(my_set)

{'a', 'b', 'c'}

In [15]:
#  Write a code to clear all elements from the set {1, 2, 3, 4, 5}
my_set = {1, 2, 3, 4, 5}
my_set.clear()
print(my_set)

set()

In [ ]:
#  Write a code to remove the element 4 from the set {1, 2, 3, 4}
my_set = {1, 2, 3, 4}
my_set.remove(4)
print(my_set)

In [35]:
#  Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}
set1 = {1, 2, 3}
set2 = {3, 4, 5}
print(set1.union(set2))

{1, 2, 3, 4, 5}

In [34]:
# Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}
set1 = {1, 2, 3}
set2 = {2, 3, 4}
print(set1.intersection(set2))

{2, 3}

In [33]:
# Write a code to create a dictionary with the keys "name", "age", and "city", and print it
my_dict = {
    "name": "Keshav",
    "age": 20,
    "city": "Delhi"
}
print(my_dict)

{'name': 'Keshav', 'age': 20, 'city': 'Delhi'}

In [16]:
# Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}
my_dict = {'name': 'John', 'age': 25}
my_dict['country'] = 'USA'
print(my_dict)

In [ ]:
#  Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}
my_dict = {'name': 'Alice', 'age': 30}
print(my_dict['name'])

In [ ]:
# Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}
my_dict = {'name': 'Bob', 'age': 22, 'city': 'New York'}
del my_dict['age']
print(my_dict)

In [ ]:
#  Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}
my_dict = {'name': 'Alice', 'city': 'Paris'}
print('city' in my_dict)

In [17]:
#  Write a code to create a list, a tuple, and a dictionary, and print them all
list = [1,2,3,4]
my_dict = {'name': 'Alice', 'city': 'Paris'}
tuple = (1,2,3,4)
print(list , my_dict , tuple)

[1, 2, 3, 4] {'name': 'Alice', 'city': 'Paris'} (1, 2, 3, 4)

In [20]:
# Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced)
import random
random_numbers = [random.randint(1, 100) for _ in range(5)]
random_numbers.sort()
print(random_numbers)

[18, 38, 50, 69, 70]

In [19]:
#  Write a code to create a list with strings and print the element at the third index
my_list = ['apple', 'banana', 'cherry', 'date', 'elderberry']
print(my_list[3])

date

In [18]:
# Write a code to combine two dictionaries into one and print the result
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
dict1.update(dict2)
print(dict1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [ ]:
#  Write a code to convert a list of strings into a set
my_list = ['apple', 'banana', 'cherry', 'apple', 'banana']
my_set = set(my_list)
print(my_set)